"""Extract territory-definition rows from the public Facility Association Ontario Manual of
Rules and Rates (final.md B2, scoped down to extraction-only).

WHAT THIS IS NOT: a premium calculator. This script never computes a dollar figure. It parses
one table type — the municipality-to-territory lookup table near the back of the manual — because
it is the only section in the document that produced clean, unambiguous, machine-parseable rows.
Every other candidate section was tried and rejected:

  - Vehicle make/model rate-group tables (pp. ~150-800+): hundreds of pages, one manufacturer per
    section, no stable column count across manufacturers — left out.
  - Annual premium / class rate group tables (e.g. p. 1100, "TERRITORY19 ANNUAL PREMIUMS"): each
    cell packs multiple rate-group values into one newline-joined string
    (e.g. "206 222 238\\n223 240 257\\n..."), so extracting a single number would mean guessing
    which of several stacked figures maps to which rate group / driving-record row. Guessing a
    number that reads as a premium is exactly what this task forbids — left out.
  - Driver class rules and endorsement charges: prose and rule text (e.g. "Rule 104"), not tabular
    data — nothing to extract as a row without paraphrasing, which is not extraction. Left out.

This is a one-time, offline extraction against a manually-downloaded copy of the source PDF (34MB,
1606 pages — too large for this environment's live-fetch path). Its output,
out/residual_manual_extract.json, is a checked-in static artifact, the same pattern already used
for data/seed/*.json: produced once by a script, versioned, not regenerated by `make run`.

Re-run manually if the manual is re-downloaded:
    .venv/bin/pip install pdfplumber
    .venv/bin/python scripts/extract_residual_manual.py --pdf /path/to/manual.pdf
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

SOURCE_URL = "https://www.facilityassociation.com/docs/ON_Manual_Effective_November_1_2025.pdf"
SOURCE_TITLE = "ON_Manual_Effective_November_1_2025"
SOURCE_EFFECTIVE_DATE = "2025-11-01"
TABLE_NAME = "Territory Definitions (County/District/Municipality to Territory and Statistical Code)"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def extract(pdf_path: Path) -> dict:
    import pdfplumber

    rows = []
    dropped = []
    pages_seen = []
    with pdfplumber.open(pdf_path) as pdf:
        n = len(pdf.pages)
        for i in range(1, n + 1):
            page = pdf.pages[i - 1]
            text = page.extract_text() or ""
            if "Municipality" not in text or "Stat" not in text:
                continue
            for table in page.extract_tables():
                if not table:
                    continue
                header = table[0]
                if not header or not any(h and "Municipality" in h for h in header):
                    continue
                pages_seen.append(i)
                for r in table[1:]:
                    if not r or len(r) != 4:
                        dropped.append({"page": i, "raw": r, "reason": "unexpected column count"})
                        continue
                    location, county, territory, stat_code = r
                    if location is None or county is None:
                        dropped.append({"page": i, "raw": r, "reason": "missing location/county cell"})
                        continue
                    territory = (territory or "").strip()
                    stat_code = (stat_code or "").strip()
                    if not territory.isdigit() or not stat_code.isdigit():
                        # e.g. "See Toronto territories" — a cross-reference, not a value.
                        # Dropped rather than guessed, per the task's own instruction.
                        dropped.append({
                            "page": i,
                            "raw": {"location": location, "county_district_municipality": county,
                                    "territory": territory, "stat_code": stat_code},
                            "reason": "territory or stat_code is not a plain integer (cross-reference, not a value)",
                        })
                        continue
                    rows.append({
                        "location": location.strip(),
                        "county_district_municipality": county.replace("\n", " ").strip(),
                        "territory": territory,
                        "stat_code": stat_code,
                        "source_page": i,
                        "source_table": TABLE_NAME,
                    })

    return {
        "rows": rows,
        "dropped": dropped,
        "page_range": [min(pages_seen), max(pages_seen)] if pages_seen else None,
        "pages_with_table": len(pages_seen),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pdf", required=True, help="Path to a locally downloaded copy of the manual PDF")
    parser.add_argument("--out", default=str(REPO_ROOT / "out" / "residual_manual_extract.json"))
    args = parser.parse_args()

    pdf_path = Path(args.pdf)
    if not pdf_path.exists():
        print(f"PDF not found: {pdf_path}", file=sys.stderr)
        return 1

    file_hash = sha256_file(pdf_path)
    result = extract(pdf_path)

    output = {
        "label": "UNVERIFIED EXTRACTION",
        "disclaimer": (
            "This is extracted rating data from a public rate manual, not a quote, estimate, or "
            "premium. Real placement in Ontario's residual auto-insurance market requires a "
            "licensed insurance broker or intermediary. FATHOM has not computed, and does not "
            "compute, any dollar figure from this data."
        ),
        "source": {
            "publisher": "Facility Association",
            "title": SOURCE_TITLE,
            "url": SOURCE_URL,
            "effective_date": SOURCE_EFFECTIVE_DATE,
            "retrieved_at": datetime.now(timezone.utc).isoformat(),
            "file_sha256": file_hash,
            "file_bytes": pdf_path.stat().st_size,
        },
        "extracted": {
            "table_name": TABLE_NAME,
            "page_range": result["page_range"],
            "pages_with_table": result["pages_with_table"],
            "row_count": len(result["rows"]),
            "rows": result["rows"],
        },
        "not_extracted": [
            {
                "category": "Vehicle make/model rate-group codes",
                "location_in_manual": "pp. ~150-800+ (Private Passenger Rate Group Tables, one manufacturer per section)",
                "reason": "No stable column structure across manufacturer sections within this timebox; would require per-manufacturer parsing logic to extract without guessing.",
            },
            {
                "category": "Annual premium / class rate group tables",
                "location_in_manual": "e.g. p. 1100, \"TERRITORY19 ANNUAL PREMIUMS\"",
                "reason": "Each table cell packs multiple stacked rate-group figures into one string with no unambiguous delimiter to the correct rate group / driving-record row. Extracting a single number here would mean guessing — refused per task instruction.",
            },
            {
                "category": "Driver class rules",
                "location_in_manual": "Section B narrative rule text (e.g. Rule 104)",
                "reason": "Prose, not tabular data. Extraction would require paraphrasing, which is not extraction.",
            },
            {
                "category": "Endorsement charges",
                "location_in_manual": "Not located within this timebox",
                "reason": "No clearly delimited endorsement-charge table was found and confirmed parseable within the 60-minute scope for this feature.",
            },
            {
                "category": f"{len(result['dropped'])} territory-table rows on pages {result['page_range'][0]}-{result['page_range'][1]}" if result["page_range"] else "rows",
                "location_in_manual": TABLE_NAME,
                "reason": "Territory or statistical code cell was a cross-reference (e.g. \"See Toronto territories\") rather than a plain value — dropped rather than guessed.",
            },
        ],
        "dropped_rows_detail": result["dropped"],
    }

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"wrote {out_path}")
    print(f"rows: {len(result['rows'])}  dropped: {len(result['dropped'])}  page range: {result['page_range']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
